version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=orion
      - MYSQL_DATABASE=orion

  server:
    restart: always
    build:
      context: orion-server
      args:
        sha: 1f3a45a84f7bcfe69d04d9c0221229932aedec6f
        database_host: db
        database_port: 3306
        database_name: orion
        database_user: root
        database_password: orion
    depends_on:
      - db

  web:
    restart: always
    ports:
      - 8080:80
    build:
      context: orion-web
      args:
        sha: ebd79013270410578c18bdbcd4894baed05cb639
        mapbox_api_token: ${MAPBOX_API_TOKEN}
    depends_on:
      - server
